[package]
name = "kfc-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
byteorder = "1.5.0"
clap = { version = "4.5.0", features = ["env", "derive"] }
zstd = "0.13"